/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'hasSubmittedDocuments' : IDL.Bool,
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PersonalInfo = IDL.Record({
  'emailId' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'surname' : IDL.Text,
  'middleName' : IDL.Text,
  'address' : IDL.Text,
  'firstName' : IDL.Text,
});
export const Registration = IDL.Record({
  'termsAcceptedAt' : Time,
  'documents' : IDL.Vec(ExternalBlob),
  'paymentMethod' : IDL.Text,
  'receipt' : IDL.Opt(ExternalBlob),
  'category' : IDL.Text,
  'phone' : IDL.Text,
  'router' : IDL.Text,
  'personalInfo' : PersonalInfo,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkIsAdmin' : IDL.Func(
      [],
      [IDL.Record({ 'isAdmin' : IDL.Bool })],
      ['query'],
    ),
  'checkUserRole' : IDL.Func(
      [],
      [IDL.Record({ 'role' : UserRole })],
      ['query'],
    ),
  'deleteCustomerRegistration' : IDL.Func([IDL.Text], [], []),
  'generateOTP' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAdminUsername' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getRegistration' : IDL.Func([IDL.Text], [IDL.Opt(Registration)], ['query']),
  'getRegistrationIds' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getRegistrationWithReceiptInfo' : IDL.Func(
      [IDL.Text],
      [Registration, IDL.Bool],
      ['query'],
    ),
  'getRegistrations' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Registration))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasReceipt' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginAdmin' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitRegistration' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Time,
        IDL.Opt(ExternalBlob),
        IDL.Vec(ExternalBlob),
      ],
      [IDL.Text],
      [],
    ),
  'updateAdminCredentials' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateCustomerPersonalInfo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateCustomerRegistration' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'verifyOTP' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'hasSubmittedDocuments' : IDL.Bool,
  });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PersonalInfo = IDL.Record({
    'emailId' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'surname' : IDL.Text,
    'middleName' : IDL.Text,
    'address' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const Registration = IDL.Record({
    'termsAcceptedAt' : Time,
    'documents' : IDL.Vec(ExternalBlob),
    'paymentMethod' : IDL.Text,
    'receipt' : IDL.Opt(ExternalBlob),
    'category' : IDL.Text,
    'phone' : IDL.Text,
    'router' : IDL.Text,
    'personalInfo' : PersonalInfo,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkIsAdmin' : IDL.Func(
        [],
        [IDL.Record({ 'isAdmin' : IDL.Bool })],
        ['query'],
      ),
    'checkUserRole' : IDL.Func(
        [],
        [IDL.Record({ 'role' : UserRole })],
        ['query'],
      ),
    'deleteCustomerRegistration' : IDL.Func([IDL.Text], [], []),
    'generateOTP' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAdminUsername' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getRegistration' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Registration)],
        ['query'],
      ),
    'getRegistrationIds' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getRegistrationWithReceiptInfo' : IDL.Func(
        [IDL.Text],
        [Registration, IDL.Bool],
        ['query'],
      ),
    'getRegistrations' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Registration))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasReceipt' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginAdmin' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitRegistration' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Time,
          IDL.Opt(ExternalBlob),
          IDL.Vec(ExternalBlob),
        ],
        [IDL.Text],
        [],
      ),
    'updateAdminCredentials' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateCustomerPersonalInfo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateCustomerRegistration' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'verifyOTP' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };